drop table if exists member cascade;

create table member(
                       id bigint generated by default as identity,
                       name varchar(255),
                       primary key (id)
);

create table board(
    id bigint generated by default as identity,
    title varchar(50),
    content blob,
    author varchar(20),
    primary key (id)
    );